title:              Manish Tripathy
email:              manish.tripathy@outlook.com
description:        Hi, I am Manish Tripathy. I am passionate about exploring and blogging tech.
handle:             "@MTripathy"
author:             Manish Tripathy
baseurl:            "/blog"
url:                ""

# Social Profiles
twitter_username:   MTripathy91
github_username:    TripathyM
facebook_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
